/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RouteMatch {
  pattern: string
  params: Record<string, string>
}
export declare function shout(input: string): string
export declare class RouteStore {
  constructor()
  insert(path: string): void
  search(path: string): RouteMatch | null
}
